export const LANDING = '/';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const BookCard = '/BookCard';
export const CardsPage = '/CardsPage';
export const Scientific = '/scientific';
export const Historical = '/historical';
export const Languages = '/languages';
export const page2 ='/auth/About_Contact_pages/page2/page2';
export const page3 ='/auth/About_Contact_pages/page3/page3';
export const page6 ='/auth/About_Contact_pages/page6/page6';
export const Contact_us ='/auth/About_Contact_pages/Contact_us/Contact_us';
export const About_us ='/auth/About_Contact_pages/About_us/About_us';

export const HOME = '/home';
export const ACCOUNT = '/account';
export const ADMIN = '/admin';
export const ADMIN_DETAILS = '/admin/:id';
export const PASSWORD_FORGET = '/pw-forget';
